### ISSUE TITLE
iframe window size issues

### ISSUE THREAD

**Issue by Visors** [mashirozx/Awesome-Deck#17]
<iframe src="https://deck.2heng.xin/embed/?name=Miracle+Rogue&code=AAECAaIHCLICrwSXBon0AqCAA6+RA7SRA5KXAwu0Ae0CzQObBYgHpAeGCcf4Ao+XA5CXA/6aAwA=" width="100%" frameborder="0" scrolling="no" class="hearthstone-deck">
</iframe>
<script>
    if ( $( "iframe" ).hasClass( "hearthstone-deck" ) ) {
        $(".hearthstone-deck").each(
			function () {
            	$(this).attr('height', $(this).width()*5/9+'px');
        	}
		);
    }
</script>
height貌似并未被配置，显示出的是默认的窗口高度

**Comment by mashirozx** [comment]
$(this).attr('height', $(this).width()*5/9+'px');设置了高度，仅需在CSS中定义宽度即可

**Comment by Visors** [comment]
底下的script部分貌似没有被执行。我现在的做法是直接在iframe里写height="500px"。

**Comment by mashirozx** [comment]
网页是否引入了jQuery

**Comment by mashirozx** [comment]
![image](https://user-images.githubusercontent.com/16148054/56866793-3e5fd680-6a10-11e9-98f4-7a3faa44af60.png)

**Comment by mashirozx** [comment]
```php
function hsdt($content) {  
    //[hsdt]Deck Name[/hsdt][hsd]Deck String[/hsd]
    $content =  str_replace('[hsdt]', '<div class="hearthstone-deck-container"><iframe src="https://deck.2heng.xin/deck/?name=', $content); 
    $content =  str_replace('[/hsdt][hsd]', '&code=', $content); 
    $content =  str_replace('[/hsd]', '" width="100%" frameborder="0" scrolling="no" allowfullscreen class="hearthstone-deck"></iframe></div>', $content); 
    return $content;
}
add_filter('the_content', 'hsdt');
```
![image](https://user-images.githubusercontent.com/16148054/56866914-90552c00-6a11-11e9-8e24-c2fd1a7a202f.png)

**Comment by Visors** [comment]
thx XD
